spring:
  application:
    name: dn-data-puller

server:
  port: 8081

dn:
  data:
    dataset:
      host: http://localhost:8080/
    aggregator:
      host: http://localhost:8082/

dataset:
  location: "E:/Practice/SpringBoot/data-nest/dataset-files/download/"